name: one-off
favicon: null
layout_spectrum: 0.8131867172196507
typography_spectrum: 0.8471851542126387
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#9D2D3C'
    - '#DDE4DD'
    - '#BCAB47'
    - '#6B574B'
    - '#160600'
  brandStrength: 0.9373161031398922
  lightness: 0.7815656727179885
  saturation: 0.6976855040993541
  rhythmicContrast: 0.34237108170054853
purpose: []
